@BASE_URL = http://localhost:3000/api/v1


###
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "maruf@gmail.com",
    "password": "1234567"
}

###
POST {{BASE_URL}}/auth/sign-up
Content-Type: application/json

{
    "fullName": "Maruf Hossain",
    "email": "maruf@gmail.com",
    "password": "1234567"
}

###
POST {{BASE_URL}}/item
Content-Type: application/json

{
    "itemName": "Salmon Fish Curry",
    "descriptions": "Bukachuda Marufer banano",
    "imageUrl": "http://localhost:3000"
}